export const LOADING_DATA = 'LOADING_DATA'
export const FETCH_GW2_CHARACTERS = 'FETCH_GW2_CHARACTERS'

//PROFIL

export const FETCH_PROFIL = 'PROFIL_LOADING'
export const CLEAR_CURRENT_PROFIL = 'CLEAR_CURRENT_PROFIL'


//login, register, logout
export const CONNECT_USER = 'CONNECT_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const DISCONNECT_USER = 'DISCONNECT_USER'
